---
title: "Publications"
description: |
  Publications that are related to Sykdomspulsen.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(data.table)
# knitcitations::cleanbib()
# knitcitations::citet("10.1371/currents.outbreaks.3c3477556808e44cf41d2511b21dc29f")
# knitcitations::citet("10.2807/1560-7917.ES.2017.22.14.30506")
# knitcitations::citet("10.1186/s12879-017-2631-2")
# # knitcitations::citet("10.1007/s40273-017-0604-3") #
# # https://scholar.google.com/citations?view_op=view_citation&hl=en&user=75oKEWoAAAAJ&cstart=20&pagesize=80&sortby=pubdate&citation_for_view=75oKEWoAAAAJ:za7pDTvVV8kC
# 
# # knitcitations::citet("10.1111/jvh.12904") #
# # knitcitations::citet("10.5588/pha.19.0002") #
# knitcitations::citet("10.1016/j.cmi.2019.02.011")
# knitcitations::citet("10.2807/1560-7917.ES.2020.25.26.2001214")
# # knitcitations::citet("10.1101/2021.10.25.21265166") #
# knitcitations::citet("10.3897/aca.4.e68891")
# 
# 
# knitcitations::write.bibtex(file="temp.bib")
```

### Publications about the Sykdomspulsen system/infrastructure

```{r echo=FALSE, warning=FALSE, results = "asis"}
d <- knitcitations::read.bibtex("publications_system_publications.bib")
print(d, .opts = list(sorting="ydnt", bib.style = "authoryear", max.names = 1, dashed = F, style = "html"))
```


### Publications that include data and/or results from the Sykdomspulsen implementation at FHI

```{r echo=FALSE, warning=FALSE, results = "asis"}
d <- knitcitations::read.bibtex("publications_data.bib")
print(d, .opts = list(sorting="ydnt", bib.style = "authoryear", max.names = 1, dashed = F, style = "html"))
```
